# Use root/example as user/password credentials
version: '3.1'

services:
  graphana:
    image: grafana/grafana:5.1.0
    ports:
       - 3000:3000

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: sevauk
      MONGO_INITDB_ROOT_PASSWORD: kronos

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sevauk
      ME_CONFIG_MONGODB_ADMINPASSWORD: kronos

